config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions

  root :to => "projects#index"

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :description, :title, :user, :asset
  validates :title, :presence => true
  validates :description, :presence => true,
  						  :length => { :minimum => 10 }
  
has_attached_file :asset

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :find_project
	before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
	before_filter :authorize_create!, :only => [:new, :create]
	before_filter :authorize_update!, :only => [:edit, :update]
	before_filter :authorize_delete!, :only => :destroy

	def new
		@ticket = @project.tickets.build
	end

	def create
		@ticket = @project.tickets.build(params[:ticket].merge!( :user => current_user))
		if @ticket.save
			flash[:notice] = "Ticket has been created. "
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been created. "
			render :action => "new"
		end
	end

	def edit

	end

	def update
		if @ticket.update_attributes(params[:ticket])
			flash[:notice] = "Ticket has been updated."
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been updated. "
			render :action => "edit"
		end
	end

	def destroy
		@ticket.destroy
		flash[:notice] = "Ticket has been deleted."
		redirect_to @project
	end

	private

		def find_project
			@project = Project.for(current_user).find(params[:project_id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The project you were looking for could not be found."
			redirect_to root_path
		end

		def find_ticket
			@ticket = @project.tickets.find(params[:id])
		end

		def authorize_create!
			if !current_user.admin? && cannot?("create tickets".to_sym, @project)
			flash[:alert] = "You cannot create tickets on this project."
			redirect_to @project
			end
		end

		def authorize_update!
			if !current_user.admin? && cannot?(:"edit tickets", @project)
				flash[:alert] = "You cannot edit tickets on this project."
				redirect_to @project
			end
		end

		def authorize_delete!
			if !current_user.admin? && cannot?(:"delete tickets", @project)
			flash[:alert] = "You cannot delete tickets from this project."
			redirect_to @project
			end
		end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket], :html => { :multipart => true } do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :asset, "File" %>
		<%= f.file_field :asset %>
	</p>
	<%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id="ticket">
	<h2><%= @ticket.title %></h2>

	<%= authorized?("edit tickets", @project) do %>
		<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
	<% end %>

	<%= authorized?("delete tickets", @project) do %>
		<%= link_to "Delete Ticket", project_ticket_path(@project, @ticket), :method => :delete, :confirm => "Are you sure you want to delete this ticket?" %>
	<% end %>


	<br><small>Created by <%= @ticket.user.email %></small>
	<%= simple_format(@ticket.description) %>

	<% if @ticket.asset.exists? %>
	<h3>Attached File</h3>
		<div class="asset">
			<p>
				<%= link_to File.basename(@ticket.asset.path), @ticket.asset.url %>
			</p>
			<p><small><%= number_to_human_size(@ticket.asset.size) %>
				(<%= @ticket.asset.content_type %>)</small></p>
		</div>
	<% end %>

	


</div>